version: '3.1'

services:

  altair-server:
    image: prodalia/altair-server:1.0.0
    ports:
      - 8080:8338
    networks:
      - altair-network
    deploy:
      restart_policy:
        condition: any
        delay: 5s

  altair-client-1:
    image: prodalia/altair-client:1.0.0
    environment:
      - TAP_ID=1
      - INET_ADDR=altair-server:8338
    networks:
      - altair-network
    deploy:
      restart_policy:
        condition: any
        delay: 5s

  altair-client-2:
    image: prodalia/altair-client:1.0.0
    environment:
      - TAP_ID=2
      - INET_ADDR=altair-server:8338
    networks:
      - altair-network
    deploy:
      restart_policy:
        condition: any
        delay: 5s

  altair-client-3:
    image: prodalia/altair-client:1.0.0
    environment:
      - TAP_ID=3
      - INET_ADDR=altair-server:8338
    networks:
      - altair-network
    deploy:
      restart_policy:
        condition: any
        delay: 5s

networks:
  altair-network: